version: '2'
services:
  quicksalesapi-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/QuickSalesAPI/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=QuickSalesAPI
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
