//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.09 at 07:47:21 PM ECT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ec.gob.sri.ws.autorizacion")
package ec.com.newsolutions.web.wsdl.sri.authorization;
